/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f4f5",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#ffb4aa",
        "secondary-fixed": "#f7d8ff",
        "surface-variant": "#e1e3e4",
        "tertiary-fixed": "#ffdf96",
        "surface-container-highest": "#e1e3e4",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#e7c268",
        "outline": "#8c716d",
        "surface-bright": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "outline-variant": "#e0bfbb",
        "on-tertiary-container": "#433200",
        "surface-dim": "#d9dadb",
        "inverse-primary": "#ffb4aa",
        "tertiary": "#765a05",
        "primary": "#ab332a",
        "secondary": "#7a4c8f",
        "on-secondary-container": "#6d4082",
        "on-tertiary-fixed": "#251a00",
        "on-primary-container": "#6f0305",
        "on-primary-fixed": "#410001",
        "tertiary-container": "#bb9944",
        "surface-container-lowest": "#ffffff",
        "surface": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "secondary-fixed-dim": "#e9b3fe",
        "background": "#f8f9fa",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#603475",
        "on-secondary-fixed": "#310146",
        "surface-container-high": "#e7e8e9",
        "secondary-container": "#e9b3fe",
        "on-secondary": "#ffffff",
        "surface-tint": "#ab332a",
        "on-surface-variant": "#58413e",
        "surface-container": "#edeeef",
        "on-surface": "#191c1d",
        "on-tertiary-fixed-variant": "#5a4400",
        "primary-container": "#ff7061",
        "error": "#ba1a1a",
        "primary-fixed": "#ffdad5",
        "on-primary-fixed-variant": "#8a1b15",
        "on-background": "#191c1d",
        "inverse-surface": "#2e3132",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding-mobile": "20px",
        "stack-lg": "48px",
        "gutter": "24px",
        "container-padding-desktop": "48px",
        "base": "8px",
        "stack-md": "24px",
        "stack-sm": "12px",
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-xl": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.03em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
